---
# some interesting files on elastic beanstalk
# /opt/elasticbeanstalk/deploy/configuration/containerconfiguration

- name: check if /opt/elasticbeanstalk/bin/get-config exists
  stat: path=/opt/elasticbeanstalk/bin/get-config
  register: elasticbeanstalk_config

- name: query environment variables
  shell: /opt/elasticbeanstalk/bin/get-config environment
  register: environment_output
  when: elasticbeanstalk_config.stat.exists

- name: set fact if config exists
  set_fact:
     elasticbeanstalk_env: "{{ environment_output.stdout | from_json }}"
  when: elasticbeanstalk_config.stat.exists

- name: set fact if config DOES NOT exists
  set_fact:
     elasticbeanstalk_env: {}
  when: not elasticbeanstalk_config.stat.exists

- name: write secrets out
  template: >
    src=templates/secrets.env.j2
    dest={{ secrets_dir | default('.') }}/secrets.env
    mode=0644
