---
# tasks file for ansible-balanced-stalk-docker

- include: assembe-secrets.yml
  tags:
    - "assemble-secrets"

- include: patch-eb-scripts.yml
  tags:
    - "patch-eb-scripts"

- include: bootstrap.yml
  tags:
    - "bootstrap"